Algoritmo "AreaRetangulo"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Calcula a área de um retângulo (base * altura)
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 17/04/2026
Var
   valorBase, valorAltura, areaCalculada: real

Inicio
   escreva("Digite a base do retângulo: ")
   leia(valorBase)
   escreva("Digite a altura do retângulo: ")
   leia(valorAltura)

   areaCalculada <- valorBase * valorAltura

   escreva("A área do retângulo é: ", areaCalculada)

Fimalgoritmo