Algoritmo "VerificaMaiorDez"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Verifica se o valor é maior que 10 ou não
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 17/04/2026
Var
   valorInformadoPeloUsuario: real

Inicio
   escreva("Digite um valor: ")
   leia(valorInformadoPeloUsuario)

   se (valorInformadoPeloUsuario > 10) entao
      escreva("É MAIOR QUE 10!")
   senao
      escreva("NÃO É MAIOR QUE 10!")
   fimse

Fimalgoritmo