Algoritmo "Exercicio20CelsiusParaFahrenheit"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Converte uma temperatura em graus Celsius para Fahrenheit.
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 19/04/2026
Var
   temperaturaEmGrausCelsius, temperaturaEmGrausFahrenheit: real

Inicio
   escreva("Digite a temperatura em Celsius: ")
   leia(temperaturaEmGrausCelsius)

   temperaturaEmGrausFahrenheit <- (temperaturaEmGrausCelsius * 9/5) + 32

   escreva("A temperatura em Fahrenheit é: ", temperaturaEmGrausFahrenheit)

Fimalgoritmo