Algoritmo "Exercicio14ConversaoMetrosCentimetros"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Leia um valor em metros e converta para centímetros.
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 19/04/2026
Var
   medidaEmMetros, medidaEmCentimetrosConvertida: real

Inicio
   escreva("Digite o valor em metros: ")
   leia(medidaEmMetros)

   medidaEmCentimetrosConvertida <- medidaEmMetros * 100

   escreva("O valor em centímetros é: ", medidaEmCentimetrosConvertida)

Fimalgoritmo