Algoritmo "Exercicio02AreaQuadrado"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Calcula a área de um quadrado a partir do lado.
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 19/04/2026
Var
   medidaDoLadoDoQuadrado, valorDaAreaCalculada: real

Inicio
   escreva("Digite o valor do lado: ")
   leia(medidaDoLadoDoQuadrado)
   valorDaAreaCalculada <- medidaDoLadoDoQuadrado * medidaDoLadoDoQuadrado
   escreva("A área do quadrado é: ", valorDaAreaCalculada)

Fimalgoritmo