Algoritmo "Exercicio03PerimetroQuadrado"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Leia o valor do lado de um quadrado e calcule o perímetro.
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 19/04/2026
Var
   medidaDoLadoDoQuadrado, valorDoPerimetroCalculado: real

Inicio
   escreva("Digite o valor do lado: ")
   leia(medidaDoLadoDoQuadrado)

   valorDoPerimetroCalculado <- 4 * medidaDoLadoDoQuadrado

   escreva("O perímetro do quadrado é: ", valorDoPerimetroCalculado)

Fimalgoritmo