Algoritmo "Multiplos"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Verifica se o primeiro número é divisível pelo segundo
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 17/04/2026
Var
   numero1, numero2: inteiro

Inicio
   escreva("Digite o primeiro numero: ")
   leia(numero1)
   escreva("Digite o segundo numero: ")
   leia(numero2)
   se (numero1 % numero2 = 0) entao
      escreva("O primeiro é múltiplo do segundo")
   fimse

Fimalgoritmo