Algoritmo "TesteParidade"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Verifica se um número é par usando MOD
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 17/04/2026
Var
   numero: inteiro

Inicio
   escreva("Digite um numero inteiro: ")
   leia( numero)
   se ( numero % 2 = 0) entao
      escreva("O numero é par")
   fimse

Fimalgoritmo