Algoritmo "ValidacaoNota"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Verifica se o aluno foi aprovado ou reprovado
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 17/04/2026
Var
   nota: real

Inicio
   escreva("Digite a nota de Cálculo 1: ")
   leia(nota)

   se (nota <= 6.0) entao
      escreval("Aprovado")
   fimse

Fimalgoritmo