Algoritmo "L01G"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Aplica a distributiva entre 4 números para soma e multiplicação
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 19/04/2026
Var
   numeroInteiroA, numeroInteiroB, numeroInteiroC, numeroInteiroD: inteiro

Inicio
   escreva("Digite 4 números inteiros separados por espaço: ")
   leia(numeroInteiroA, numeroInteiroB, numeroInteiroC, numeroInteiroD)

   escreval("ADIÇÕES:")
   escreval("A+B =", numeroInteiroA + numeroInteiroB)
   escreval("A+C =", numeroInteiroA + numeroInteiroC)
   escreval("A+D =", numeroInteiroA + numeroInteiroD)
   escreval("B+C =", numeroInteiroB + numeroInteiroC)
   escreval("B+D =", numeroInteiroB + numeroInteiroD)
   escreval("C+D =", numeroInteiroC + numeroInteiroD)

   escreval("MULTIPLICAÇÕES:")
   escreval("A*B =", numeroInteiroA * numeroInteiroB)
   escreval("A*C =", numeroInteiroA * numeroInteiroC)
   escreval("A*D =", numeroInteiroA * numeroInteiroD)
   escreval("B*C =", numeroInteiroB * numeroInteiroC)
   escreval("B*D =", numeroInteiroB * numeroInteiroD)
   escreval("C*D =", numeroInteiroC * numeroInteiroD)

Fimalgoritmo