Algoritmo "L02K"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Lê um número e o apresenta apenas se ele não for maior que 3.
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 19/04/2026
Var
   numeroInteiroLido: inteiro

Inicio
   escreva("Digite um número: ")
   leia(numeroInteiroLido)

   se (nao (numeroInteiroLido > 3)) entao
      escreva("Valor: ", numeroInteiroLido)
   fimse

Fimalgoritmo