Algoritmo "L03D"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Apresenta todos os números ímpares entre 0 e 20 com verificação SE.
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 19/04/2026
Var
   numeroInteiroParaVerificacao: inteiro

Inicio
   numeroInteiroParaVerificacao <- 0

   enquanto (numeroInteiroParaVerificacao <= 20) faca
      se (numeroInteiroParaVerificacao % 2 <> 0) entao
         escreval("O número ", numeroInteiroParaVerificacao, " é ímpar.")
      fimse
      numeroInteiroParaVerificacao <- numeroInteiroParaVerificacao + 1
   fimenquanto

Fimalgoritmo






