Algoritmo "L05E"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Apresenta os números ímpares entre 0 e 20 com verificação lógica.
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 19/04/2026
Var
   valorContadorDeZeroAVinte: inteiro

Inicio
   para valorContadorDeZeroAVinte de 0 ate 20 faca
      se (valorContadorDeZeroAVinte % 2 <> 0) entao
         escreval("O número ", valorContadorDeZeroAVinte, " é ÍMPAR.")
      fimse
   fimpara

Fimalgoritmo