Algoritmo "L05F"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Apresenta números divisíveis por 4 menores que 200.
// Autor(a)    : Grasiely Aparecida Martins
// Data atual  : 19/04/2026
Var
   contadorNumericoAteDuzentos: inteiro

Inicio
   para contadorNumericoAteDuzentos de 1 ate 199 faca
      se (contadorNumericoAteDuzentos % 4 = 0) entao
         escreval(contadorNumericoAteDuzentos, " é divisível por 4.")
      fimse
   fimpara

Fimalgoritmo